#!/usr/bin/env bash
# Write training/Modelfile.<name> with FROM + SYSTEM (from .mdc build or existing file).
#
#   bash training/write-modelfile-with-rules.sh forth-qwen-core qwen2.5-coder:0.5b-instruct \
#     --system output/frules-ollama-system-core.txt
#
#   bash training/write-modelfile-with-rules.sh forth-qwen-core qwen2.5-coder:0.5b-instruct gforth core
#
#   ollama pull qwen2.5-coder:0.5b-instruct
#   ollama create forth-qwen-core -f training/Modelfile.forth-qwen-core
#   ollama run forth-qwen-core

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

NAME=""
FROM=""
SYSTEM_TXT=""
DIALECT="gforth"
PROFILE="full"
NUM_CTX="16384"

usage() {
  sed -n '2,12p' "$0"
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --system|-s)
      SYSTEM_TXT="$2"
      shift 2
      ;;
    --num-ctx)
      NUM_CTX="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    gforth|ans)
      DIALECT="$1"
      shift
      ;;
    full|core)
      PROFILE="$1"
      shift
      ;;
    *)
      if [ -z "$NAME" ]; then
        NAME="$1"
      elif [ -z "$FROM" ]; then
        FROM="$1"
      else
        echo "unexpected arg: $1" >&2
        usage
      fi
      shift
      ;;
  esac
done

[ -n "$NAME" ] && [ -n "$FROM" ] || usage

if [ -z "$SYSTEM_TXT" ]; then
  SYSTEM_TXT="${ROOT}/output/frules-ollama-system.txt"
  bash "$ROOT/scripts/build-ollama-system.sh" "$DIALECT" "$PROFILE" -o "$SYSTEM_TXT"
else
  case "$SYSTEM_TXT" in
    /*) ;;
    *) SYSTEM_TXT="$ROOT/$SYSTEM_TXT" ;;
  esac
  [ -f "$SYSTEM_TXT" ] || { echo "missing system file: $SYSTEM_TXT" >&2; exit 1; }
fi

if grep -q '"""' "$SYSTEM_TXT" 2>/dev/null; then
  echo "error: rules text contains triple quotes — fix source .mdc" >&2
  exit 1
fi

OUT_MF="$ROOT/training/Modelfile.${NAME}"
{
  echo "# Generated by training/write-modelfile-with-rules.sh — do not edit by hand"
  echo "# SYSTEM from: $SYSTEM_TXT"
  echo "FROM ${FROM}"
  echo ""
  echo "PARAMETER temperature 0.2"
  echo "PARAMETER num_ctx ${NUM_CTX}"
  echo ""
  echo 'SYSTEM """'
  cat "$SYSTEM_TXT"
  echo '"""'
} > "$OUT_MF"

BYTES="$(wc -c < "$SYSTEM_TXT" | tr -d ' ')"
echo "wrote: $OUT_MF (system ${BYTES} bytes, num_ctx=${NUM_CTX})"
echo "  ollama pull qwen2.5-coder:0.5b-instruct   # if FROM is that tag and not pulled yet"
echo "  ollama create ${NAME} -f $OUT_MF"
echo "  ollama run ${NAME}"
