#!/usr/bin/env python3
"""Build scripts/challenge_catalog.py from compact challenge tuples."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

OUT = Path(__file__).resolve().parent / "challenge_catalog.py"


def _seq(field) -> list[str]:
    """Normalize spec/style/tests: single str or tuple of str -> list."""
    if isinstance(field, str):
        return [field]
    return list(field)


def ch(t: tuple) -> dict:
    extra = t[14] if len(t) > 14 else ""
    return {
        "id": t[0],
        "slug": t[1],
        "word": t[2],
        "stack": t[3],
        "pattern_key": t[4],
        "cognitive": t[5],
        "source": t[6],
        "url": t[7],
        "taxonomy_block": t[8],
        "scaffold": t[9],
        "title": t[10],
        "spec": _seq(t[11]),
        "style": _seq(t[12]),
        "tests": _seq(t[13]),
        "extra_scaffold": extra,
    }


LINK = dedent(
    """
    : ch-val!  ( n i -- )  swap cells ch-vals + ! ;
    : ch-next! ( n i -- )  swap cells ch-nexts + ! ;
    """
).strip()

TREE = dedent(
    """
    : ch-t! ( n off -- )  swap cells ch-tree + ! ;
    """
).strip()

RAW: list[tuple] = []

# fmt: (id, slug, word, stack, pattern_key, cog, src, url, tax, scaf, title, spec, style, tests[, extra])

def extend(*rows: tuple) -> None:
    RAW.extend(rows)


extend(
    # scalar-math 1-8
    (1, "reverse-int", "reverse-int", "( n -- n' )", "reverse-signed-digits", 3, "leetcode",
     "https://leetcode.com/problems/reverse-integer/", "scalar-math", "scalar", "Reverse Integer",
     ("Reverse signed cell digits; return 0 if reversed value exceeds 32-bit signed range.",
      "Negative sign preserved."),
     ("Use arithmetic, not string conversion.", "Document stack effect on every helper."),
     ("123 reverse-int -> 321", "-120 reverse-int -> -21", "1530 reverse-int -> 351",
      "0 reverse-int -> 0", "1000000003 reverse-int -> 0")),
    (2, "palindrome-num", "palindrome-num?", "( n -- flag )", "palindrome-number-check", 3, "leetcode",
     "https://leetcode.com/problems/palindrome-number/", "scalar-math", "scalar", "Palindrome Number",
     ("Return TRUE iff n reads the same forward and backward.", "Negative numbers are not palindromes."),
     ("No string allocation required.", "Return true/false not 1/0."),
     ("121 palindrome-num? -> true", "-121 palindrome-num? -> false", "10 palindrome-num? -> false",
      "0 palindrome-num? -> true", "1221 palindrome-num? -> true")),
    (3, "pow-x-n", "ipow", "( base exp -- n )", "integer-exponentiation", 4, "leetcode",
     "https://leetcode.com/problems/powx-n/", "scalar-math", "scalar", "Pow(x, n)",
     ("Raise base to non-negative exp using fast exponentiation.", "Assume result fits in a cell."),
     ("Binary exponentiation preferred.", "exp=0 always returns 1."),
     ("2 10 ipow -> 1024", "3 0 ipow -> 1", "5 3 ipow -> 125", "2 16 ipow -> 65536", "10 2 ipow -> 100")),
    (4, "sqrt-int", "isqrt", "( n -- r )", "integer-sqrt-floor", 4, "codewars",
     "https://www.codewars.com/kata/integer-square-root", "scalar-math", "scalar", "Integer Square Root",
     ("Return floor(sqrt(n)) for non-negative n.", "No floating point."),
     ("Binary search or Newton iteration.", "n=0 returns 0."),
     ("0 isqrt -> 0", "1 isqrt -> 1", "8 isqrt -> 2", "15 isqrt -> 3", "16 isqrt -> 4", "99 isqrt -> 9")),
    (5, "is-prime", "prime?", "( n -- flag )", "primality-trial", 5, "kata",
     "https://www.codewars.com/kata/is-this-a-prime-number", "scalar-math", "scalar", "Is Prime",
     ("Return TRUE iff n>=2 and n has no divisors except 1 and itself."),
     ("Trial division is fine.", "Return true/false."),
     ("0 prime? -> false", "1 prime? -> false", "2 prime? -> true", "17 prime? -> true",
      "18 prime? -> false", "97 prime? -> true")),
    (6, "fib-nth", "fib", "( n -- f )", "fibonacci-nth-term", 3, "rosetta",
     "https://rosettacode.org/wiki/Fibonacci_sequence", "scalar-math", "scalar", "Nth Fibonacci",
     ("Return F(n) with F(0)=0, F(1)=1.", "Assume n<=30 for cell safety."),
     ("Iterative preferred.", "No magic indices in loop body."),
     ("0 fib -> 0", "1 fib -> 1", "5 fib -> 5", "10 fib -> 55", "20 fib -> 6765")),
    (7, "gcd", "gcd", "( a b -- g )", "euclid-gcd", 3, "rosetta",
     "https://rosettacode.org/wiki/Greatest_common_divisor", "scalar-math", "scalar", "Greatest Common Divisor",
     ("Return gcd(a,b) using Euclidean algorithm.", "gcd(0,b) returns abs(b)."),
     ("Keep stack depth shallow.", "Use ABS on result."),
     ("48 18 gcd -> 6", "101 10 gcd -> 1", "0 7 gcd -> 7", "-12 8 gcd -> 4", "270 192 gcd -> 6")),
    (8, "lcm", "lcm", "( a b -- m )", "least-common-multiple", 4, "rosetta",
     "https://rosettacode.org/wiki/Least_common_multiple", "scalar-math", "scalar", "Least Common Multiple",
     ("Return lcm(a,b) = abs(a*b)/gcd(a,b).", "Either argument may be zero (return 0)."),
     ("Reuse gcd or inline Euclid.", "Handle zero without divide-by-zero."),
     ("4 6 lcm -> 12", "21 6 lcm -> 42", "0 5 lcm -> 0", "7 7 lcm -> 7", "9 12 lcm -> 36")),
)

# strings 9-16
extend(
    (9, "longest-common-prefix", "lcp-len",
     "( c-addr1 u1 c-addr2 u2 -- len )", "longest-common-prefix-length", 4, "leetcode",
     "https://leetcode.com/problems/longest-common-prefix/", "strings", "string", "Longest Common Prefix Length",
     ("Given two counted strings, return length of longest shared prefix.", "Empty prefix returns 0."),
     ("Use ch-setup for test inputs.", "No allocation beyond scaffold buffer."),
     ('s" flower" ch-setup s" flow" ch-setup lcp-len -> 4',
      's" dog" ch-setup s" cat" ch-setup lcp-len -> 0',
      's" abc" ch-setup s" abc" ch-setup lcp-len -> 3',
      's" " ch-setup s" abc" ch-setup lcp-len -> 0')),
    (10, "string-to-int", "atoi", "( c-addr u -- n )", "string-to-integer-parse", 5, "leetcode",
     "https://leetcode.com/problems/string-to-integer-atoi/", "strings", "string", "String to Integer",
     ("Parse optional leading sign and digits into signed cell.", "Stop at first non-digit; non-digit start -> 0."),
     ("Use ch-setup in tests.", "Clamp overflow to cell limits for benchmark."),
     ('s" 42" ch-setup atoi -> 42', 's"   -7" ch-setup atoi -> -7',
      's" 4193abc" ch-setup atoi -> 4193', 's" abc" ch-setup atoi -> 0', 's" +12" ch-setup atoi -> 12')),
    (11, "last-word-len", "last-word-len", "( c-addr u -- len )", "last-word-length", 3, "leetcode",
     "https://leetcode.com/problems/length-of-last-word/", "strings", "string", "Length of Last Word",
     ("Return length of last whitespace-delimited word.", "Trailing spaces may appear."),
     ("Treat bl as separator only.", "Use ch-setup."),
     ('s" Hello World" ch-setup last-word-len -> 5',
      's" fly me to the moon " ch-setup last-word-len -> 4',
      's" a" ch-setup last-word-len -> 1', 's" " ch-setup last-word-len -> 0')),
    (12, "count-and-say", "count-say", "( c-addr u -- c-addr2 u2 )", "count-and-say-next", 6, "leetcode",
     "https://leetcode.com/problems/count-and-say/", "strings", "string", "Count and Say Next",
     ("Transform run-length string to next term (1->11, 11->21).", "Return result in ch-buf as counted string."),
     ("Factor digit-run encoder.", "Result valid until next call."),
     ('s" 1" ch-setup count-say s" 11" expect-str-eq ->',
      's" 11" ch-setup count-say s" 21" expect-str-eq ->',
      's" 21" ch-setup count-say s" 1211" expect-str-eq ->')),
    (13, "strstr", "strstr-idx", "( h-addr hu n-addr nu -- idx )", "substring-first-index", 4, "leetcode",
     "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", "strings", "string",
     "Find Needle Index",
     ("Return 0-based index of first occurrence of needle in haystack.", "Return -1 if absent."),
     ("Naive scan acceptable.", "Both strings via ch-setup copies."),
     ('s" hello" ch-setup s" ll" ch-setup strstr-idx -> 2',
      's" hello" ch-setup s" z" ch-setup strstr-idx -> -1',
      's" aa" ch-setup s" a" ch-setup strstr-idx -> 0',
      's" abc" ch-setup s" bc" ch-setup strstr-idx -> 1')),
    (14, "multiply-strings", "str-mul", "( a-addr au b-addr bu -- c-addr cu )", "decimal-string-multiply", 7,
     "leetcode", "https://leetcode.com/problems/multiply-strings/", "strings", "string", "Multiply String Numbers",
     ("Multiply two non-negative decimal digit strings.", "Return product as counted string in ch-buf."),
     ("Grade-school multiply OK.", "No ANS numeric conversion of whole string."),
     ('s" 2" ch-setup s" 3" ch-setup str-mul s" 6" expect-str-eq ->',
      's" 123" ch-setup s" 456" ch-setup str-mul s" 56088" expect-str-eq ->',
      's" 0" ch-setup s" 999" ch-setup str-mul s" 0" expect-str-eq ->')),
    (15, "longest-pal-sub", "longest-pal-len", "( c-addr u -- len )", "longest-palindrome-substring-len", 6,
     "leetcode", "https://leetcode.com/problems/longest-palindromic-substring/", "strings", "string",
     "Longest Palindrome Length",
     ("Return length of longest palindromic substring.", "Single char counts as length 1."),
     ("Expand-around-center or DP.", "Use ch-setup."),
     ('s" babad" ch-setup longest-pal-len -> 3', 's" cbbd" ch-setup longest-pal-len -> 2',
      's" a" ch-setup longest-pal-len -> 1', 's" racecar" ch-setup longest-pal-len -> 7')),
    (16, "valid-anagram", "anagram?", "( a-addr au b-addr bu -- flag )", "valid-anagram-check", 3, "leetcode",
     "https://leetcode.com/problems/valid-anagram/", "strings", "string", "Valid Anagram",
     ("Return TRUE iff two strings are anagrams (same multiset of chars).", "Assume lowercase a-z in tests."),
     ("O(n) count table.", "Use ch-setup."),
     ('s" anagram" ch-setup s" nagaram" ch-setup anagram? -> true',
      's" rat" ch-setup s" car" ch-setup anagram? -> false',
      's" a" ch-setup s" a" ch-setup anagram? -> true',
      's" ab" ch-setup s" ba" ch-setup anagram? -> true')),
)

# arrays-hash 17-24
extend(
    (17, "two-sum-pair", "two-sum?", "( target a b -- flag )", "two-sum-pair-exists", 3, "leetcode",
     "https://leetcode.com/problems/two-sum/", "arrays-hash", "scalar", "Two Sum Pair",
     ("Return TRUE if a+b equals target.", "Exactly two values on stack."),
     ("One comparison after add.", "Return true/false."),
     ("9 2 7 two-sum? -> true", "9 2 6 two-sum? -> false", "0 5 -5 two-sum? -> true", "15 10 5 two-sum? -> true")),
    (18, "remove-dup-sorted", "dedup-len", "( -- len )", "remove-duplicates-sorted-len", 4, "leetcode",
     "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "arrays-hash", "cell-array",
     "Remove Duplicates Length",
     ("Array ch@/ch! length ch-n sorted non-decreasing.", "Return new length with unique values kept at front."),
     ("In-place overwrite; no second array.", "Use preloaded sorted array."),
     ("dedup-len -> 4", "ch@ 0 -> 1", "ch@ 3 -> 3"),
     "1 0 ch!  1 1 ch!  2 2 ch!  3 3 ch!  3 4 ch!\n5 constant ch-n"),
    (19, "remove-element", "remove-val-len", "( val -- len )", "remove-element-count", 3, "leetcode",
     "https://leetcode.com/problems/remove-element/", "arrays-hash", "cell-array", "Remove Element Count",
     ("Remove all cells equal to val from ch-data[0..ch-n).", "Return new length; order of survivors preserved."),
     ("In-place compaction.", "val on stack."),
     ("3 remove-val-len -> 2", "ch@ 0 -> 2", "ch@ 1 -> 2"),
     "3 0 ch!  2 1 ch!  2 2 ch!  3 3 ch!\n4 constant ch-n"),
    (20, "first-missing-pos", "first-missing", "( -- n )", "first-missing-positive", 6, "leetcode",
     "https://leetcode.com/problems/first-missing-positive/", "arrays-hash", "cell-array", "First Missing Positive",
     ("Return smallest positive integer absent from ch-data.", "Array length ch-n; values may repeat."),
     ("O(n) preferred for small n.", "Uses ch-n preloaded array."),
     ("first-missing -> 2"),
     "3 0 ch!  4 1 ch!  -1 2 ch!  1 3 ch!\n4 constant ch-n"),
    (21, "next-permutation", "next-perm?", "( -- flag )", "next-permutation-step", 7, "leetcode",
     "https://leetcode.com/problems/next-permutation/", "arrays-hash", "cell-array", "Next Permutation",
     ("Transform ch-data[0..ch-n) to next lexicographic permutation in place.", "Return FALSE if last permutation."),
     ("Standard algorithm; mutate ch-data.", "Return true/false."),
     ("next-perm? -> true", "ch@ 0 -> 1", "ch@ 1 -> 3", "ch@ 2 -> 2"),
     "1 0 ch!  2 1 ch!  3 2 ch!\n3 constant ch-n"),
    (22, "sort-colors", "sort-colors", "( -- )", "dutch-national-flag-sort", 5, "leetcode",
     "https://leetcode.com/problems/sort-colors/", "arrays-hash", "cell-array", "Sort Colors",
     ("Sort ch-data[0..ch-n) containing only 0,1,2 in place.", "One pass preferred."),
     ("Three-way partition.", "Mutates ch-data."),
     ("sort-colors", "ch@ 0 -> 0", "ch@ 4 -> 2"),
     "2 0 ch!  0 1 ch!  2 2 ch!  1 3 ch!  0 4 ch!\n5 constant ch-n"),
    (23, "contains-dup", "has-dup?", "( -- flag )", "contains-duplicate-flag", 3, "leetcode",
     "https://leetcode.com/problems/contains-duplicate/", "arrays-hash", "cell-array", "Contains Duplicate",
     ("Return TRUE if any value appears twice in ch-data[0..ch-n)."),
     ("O(n^2) OK for small n.", "Return true/false."),
     ("has-dup? -> true"),
     "1 0 ch!  2 1 ch!  3 2 ch!  1 3 ch!\n4 constant ch-n"),
    (24, "majority-element", "majority", "( -- n )", "majority-element-boyer", 4, "leetcode",
     "https://leetcode.com/problems/majority-element/", "arrays-hash", "cell-array", "Majority Element",
     ("Return element appearing more than n/2 times in ch-data.", "Majority always exists in tests."),
     ("Boyer-Moore vote.", "Uses ch-n."),
     ("majority -> 2"),
     "2 0 ch!  2 1 ch!  1 2 ch!  2 3 ch!  2 4 ch!\n5 constant ch-n"),
)

# two-pointers 25-31
extend(
    (25, "max-area", "max-area", "( h1 h2 w -- area )", "container-max-water", 5, "leetcode",
     "https://leetcode.com/problems/container-with-most-water/", "two-pointers", "scalar", "Container With Most Water",
     ("Given two heights and width between them, return min(h1,h2)*w.", "Benchmark uses scalar heights on stack."),
     ("No nested loops required for single-width case.", "Keep stack <= 4."),
     ("1 2 3 max-area -> 3", "4 3 5 max-area -> 15", "7 7 10 max-area -> 70", "1 8 6 max-area -> 6")),
    (26, "three-sum-count", "three-sum-count", "( target -- count )", "three-sum-triplet-count", 6, "leetcode",
     "https://leetcode.com/problems/3sum/", "two-pointers", "cell-array", "Three Sum Count",
     ("Count unique triplets in ch-data summing to target.", "Each index used at most once per triplet."),
     ("Sort then two-pointer.", "Uses preloaded array."),
     ("0 three-sum-count -> 1"),
     "-1 0 ch!  0 1 ch!  1 2 ch!\n3 constant ch-n"),
    (27, "three-sum-closest", "three-sum-closest", "( target -- sum )", "three-sum-closest-sum", 6, "leetcode",
     "https://leetcode.com/problems/3sum-closest/", "two-pointers", "cell-array", "Three Sum Closest",
     ("Return sum of three distinct elements closest to target.", "Tie: smaller absolute difference wins."),
     ("Sort + two pointers.", "Uses ch-data preload."),
     ("1 three-sum-closest -> 2"),
     "-1 2 1 ch!\n3 constant ch-n"),
    (28, "trap-rain", "trap-rain", "( -- vol )", "trapping-rain-water-volume", 7, "leetcode",
     "https://leetcode.com/problems/trapping-rain-water/", "two-pointers", "cell-array", "Trapping Rain Water",
     ("Return trapped water volume for height array ch-data[0..ch-n)."),
     ("Two-pointer or prefix max.", "Uses preloaded heights."),
     ("trap-rain -> 6"),
     "0 1 0 2 1 0 1 3 2 1 2 1 heights\n0 0 ch!  1 1 ch!  0 2 ch!  2 3 ch!  1 4 ch!\n0 5 ch!  1 6 ch!  3 7 ch!  2 8 ch!  1 9 ch!  2 10 ch!  1 11 ch!\n12 constant ch-n"),
    (29, "merge-sorted", "merge-into", "( -- len )", "merge-sorted-arrays", 4, "leetcode",
     "https://leetcode.com/problems/merge-sorted-array/", "two-pointers", "cell-array", "Merge Sorted Arrays",
     ("Merge ch-a and ch-b (each sorted) into front of ch-data.", "Return total length."),
     ("Two-finger merge.", "Preload two segments."),
     ("merge-into -> 6", "ch@ 5 -> 6"),
     "1 0 ch!  2 1 ch!  3 2 ch!  2 3 ch!  5 4 ch!  6 5 ch!\n6 constant ch-n\n4 constant ch-a-len"),
    (30, "sort-by-parity", "sort-parity", "( -- )", "sort-array-by-parity", 4, "leetcode",
     "https://leetcode.com/problems/sort-array-by-parity/", "two-pointers", "cell-array", "Sort By Parity",
     ("Reorder ch-data so evens precede odds.", "Relative order within parity groups may change."),
     ("Two-pointer swap.", "In-place."),
     ("sort-parity", "ch@ 0 -> 2", "ch@ 3 -> 3"),
     "3 0 ch!  1 1 ch!  2 2 ch!  4 3 ch!\n4 constant ch-n"),
    (31, "remove-pal-sub", "remove-pal-sub", "( c-addr u -- c-addr2 u2 )", "remove-palindrome-substring", 5,
     "leetcode", "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/", "two-pointers", "string",
     "Remove Adjacent Duplicates",
     ("Remove all adjacent equal char pairs until stable.", "Return result in ch-buf."),
     ("Stack or two-pointer in buffer.", "Use ch-setup."),
     ('s" abbaca" ch-setup remove-pal-sub s" ca" expect-str-eq ->',
      's" azxxzy" ch-setup remove-pal-sub s" ay" expect-str-eq ->',
      's" a" ch-setup remove-pal-sub s" a" expect-str-eq ->'),
     ""),
)

# stack-queue 32-37
extend(
    (32, "min-stack", "min-push", "( n -- )", "min-stack-push", 5, "leetcode",
     "https://leetcode.com/problems/min-stack/", "stack-queue", "cell-array", "Min Stack Push",
     ("Push n onto internal stack; companion word min-top returns current minimum."),
     ("Implement min-push and min-top.", "Use ch-data as stack with ch-sp index."),
     ("1 min-push 0 min-push -1 min-push min-top -> -1", "2 min-push min-top -> -1"),
     "variable ch-sp\n0 ch-sp !\n: min-top ( -- n ) ch-sp @ 1- ch@ ;"),
    (33, "valid-brackets", "brackets?", "( c-addr u -- flag )", "valid-bracket-mixed", 5, "leetcode",
     "https://leetcode.com/problems/valid-parentheses/", "stack-queue", "string", "Valid Brackets Mixed",
     ("Return TRUE iff (), [], {} are properly nested and matched.", "Differs from round-only seed challenge."),
     ("Use a counter/stack for three kinds.", "Return true/false."),
     ('s" ()[]{} " ch-setup brackets? -> true', 's" ([)]" ch-setup brackets? -> false',
      's" {[]}" ch-setup brackets? -> true', 's" " ch-setup brackets? -> true',
      's" (]" ch-setup brackets? -> false')),
    (34, "eval-rpn", "eval-rpn", "( c-addr u -- n )", "evaluate-reverse-polish", 6, "leetcode",
     "https://leetcode.com/problems/evaluate-reverse-polish-notation/", "stack-queue", "string", "Evaluate RPN",
     ("Evaluate space-separated RPN expression with + - * / on integers.", "Division truncates toward zero."),
     ("Use value stack.", "Use ch-setup for input string."),
     ('s" 2 1 + " ch-setup eval-rpn -> 3', 's" 4 13 5 / + " ch-setup eval-rpn -> 6',
      's" 10 6 9 3 + -11 * / * 17 + 5 + " ch-setup eval-rpn -> 12')),
    (35, "daily-temp", "daily-temp", "( -- )", "daily-temperatures-span", 6, "leetcode",
     "https://leetcode.com/problems/daily-temperatures/", "stack-queue", "cell-array", "Daily Temperatures",
     ("Fill ch-out[i] with days until warmer temperature after day i.", "Last days get 0."),
     ("Monotonic stack.", "Preload temps in ch-data, ch-out same size."),
     ("daily-temp", "ch-out@ 1 -> 1", "ch-out@ 4 -> 0"),
     "73 0 ch!  74 1 ch!  75 2 ch!  71 3 ch!  69 4 ch!  72 5 ch!  76 6 ch!  73 7 ch!\n8 constant ch-n\ncreate ch-out 16 cells allot\n: ch-out@ ( i -- n ) cells ch-out + @ ;\n: ch-out! ( n i -- ) cells ch-out + ! ;"),
    (36, "decode-string-len", "decode-len", "( c-addr u -- len )", "decode-string-length", 7, "leetcode",
     "https://leetcode.com/problems/decode-string/", "stack-queue", "string", "Decode String Length",
     ("Return length of decoded k[encoded] pattern (digits and letters only).", "Do not materialize full string."),
     ("Use count stack.", "Use ch-setup."),
     ('s" 3[a]2[bc]" ch-setup decode-len -> 7', 's" abc3[cd]xyz" ch-setup decode-len -> 9',
      's" a" ch-setup decode-len -> 1')),
    (37, "asteroid-collision", "asteroid-survive", "( -- count )", "asteroid-collision-count", 6, "leetcode",
     "https://leetcode.com/problems/asteroid-collision/", "stack-queue", "cell-array", "Asteroid Collision",
     ("Simulate collisions on ch-data signed sizes; return surviving count.", "Positive moves right, negative left."),
     ("Stack simulation.", "Preload asteroids."),
    ("asteroid-survive -> 2"),
     "5 0 ch!  10 1 ch!  -5 2 ch!\n3 constant ch-n"),
)

# binary-search 38-44
extend(
    (38, "search-insert", "search-insert", "( key -- idx )", "search-insert-position", 3, "leetcode",
     "https://leetcode.com/problems/search-insert-position/", "binary-search", "cell-array", "Search Insert Position",
     ("Return index where key belongs in sorted ch-data[0..ch-n).", "Equal key returns its index."),
     ("Binary search.", "Sorted preload."),
     ("5 search-insert -> 2", "2 search-insert -> 1", "7 search-insert -> 4", "0 search-insert -> 0"),
     "1 0 ch!  3 1 ch!  5 2 ch!  6 3 ch!\n4 constant ch-n"),
    (39, "search-rotated", "search-rotated", "( key -- idx )", "search-rotated-sorted", 6, "leetcode",
     "https://leetcode.com/problems/search-in-rotated-sorted-array/", "binary-search", "cell-array",
     "Search Rotated Sorted Array",
     ("Return index of key in rotated sorted distinct array.", "Return -1 if absent."),
     ("Modified binary search.", "Preloaded rotated array."),
     ("0 search-rotated -> 4", "3 search-rotated -> -1", "4 search-rotated -> 5"),
     "4 0 ch!  5 1 ch!  6 2 ch!  7 3 ch!  0 1 ch!  2 5 ch!\n6 constant ch-n"),
    (40, "find-min-rotated", "find-min-rot", "( -- n )", "find-minimum-rotated", 5, "leetcode",
     "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "binary-search", "cell-array",
     "Find Minimum Rotated",
     ("Return minimum element in rotated sorted ch-data with distinct values."),
     ("Binary search on rotation.", "Uses ch-n."),
     ("find-min-rot -> 1"),
     "3 0 ch!  4 1 ch!  5 2 ch!  1 3 ch!  2 4 ch!\n5 constant ch-n"),
    (41, "search-range", "search-range", "( key -- lo hi )", "search-first-last-position", 5, "leetcode",
     "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", "binary-search",
     "cell-array", "Search Range",
     ("Return lo hi indices of key in sorted ch-data.", "Return -1 -1 if absent."),
     ("Two binary searches.", "Sorted with duplicates OK."),
     ("8 search-range -> 3 4", "6 search-range -> -1 -1"),
     "5 0 ch!  7 1 ch!  7 2 ch!  8 3 ch!  8 4 ch!  10 5 ch!\n6 constant ch-n"),
    (42, "search-matrix", "matrix-search?", "( key -- flag )", "search-2d-matrix", 5, "leetcode",
     "https://leetcode.com/problems/search-a-2d-matrix/", "binary-search", "grid", "Search 2D Matrix",
     ("Return TRUE if key exists in row-major sorted grid.", "Each row sorted; first of row > last of prev."),
     ("Treat as 1D sorted or stair search.", "Uses ch-grid@."),
     ("3 matrix-search? -> true", "13 matrix-search? -> false"),
     "1 0 0 ch-grid!  3 1 0 ch-grid!  5 2 0 ch-grid!\n10 0 1 ch-grid!  11 1 1 ch-grid!  16 2 1 ch-grid!\n13 0 2 ch-grid!  14 1 2 ch-grid!  15 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (43, "sqrt-binary", "isqrt-n", "( n -- r )", "sqrt-binary-search", 4, "leetcode",
     "https://leetcode.com/problems/sqrtx/", "binary-search", "scalar", "Sqrt x Binary",
     ("Return floor(sqrt(n)) for non-negative n.", "Binary search variant of isqrt."),
     ("No floating point.", "Distinct from scalar isqrt pattern key."),
     ("0 isqrt-n -> 0", "4 isqrt-n -> 2", "8 isqrt-n -> 2", "17 isqrt-n -> 4")),
    (44, "peak-index", "peak-idx", "( -- idx )", "peak-index-mountain", 4, "leetcode",
     "https://leetcode.com/problems/peak-index-in-a-mountain-array/", "binary-search", "cell-array",
     "Peak Index Mountain",
     ("Return index of peak in bitonic array (strictly increases then decreases).", "Peak element guaranteed unique."),
     ("Binary search on slope.", "Preload mountain array."),
     ("peak-idx -> 3"),
     "0 1 0 ch!  2 1 ch!  5 2 ch!  3 3 ch!  1 4 ch!\n5 constant ch-n"),
)

# linked-structure 45-51
extend(
    (45, "merge-two-lists", "merge-lists", "( -- head )", "merge-two-sorted-lists", 5, "leetcode",
     "https://leetcode.com/problems/merge-two-sorted-lists/", "linked-structure", "linked-cells",
     "Merge Two Sorted Lists",
     ("Merge lists starting ch-head-a and ch-head-b; return merged head index.", "Nodes indexed 1..N, 0=nil."),
     ("Reuse node indices.", "Define ch-val!/ch-next! in extra scaffold."),
     ("merge-lists -> 1",),
     LINK + "\n1 2 1 ch-val! 1 ch-next!\n3 0 2 ch-val! 0 ch-next!\n2 4 3 ch-val! 3 ch-next!\n4 0 4 ch-val! 0 ch-next!\n1 constant ch-head-a\n2 constant ch-head-b"),
    (46, "has-cycle", "has-cycle?", "( head -- flag )", "linked-list-cycle-detect", 5, "leetcode",
     "https://leetcode.com/problems/linked-list-cycle/", "linked-structure", "linked-cells", "Linked List Cycle",
     ("Return TRUE if list from head index contains a cycle.", "Floyd tortoise/hare on indices."),
     ("Return true/false.", "Preload cyclic list."),
     ("3 has-cycle? -> true", "4 has-cycle? -> false"),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 1 3 ch-val! 1 ch-next!\n3 constant ch-head-cyclic\n1 10 4 ch-val! 0 ch-next!\n4 constant ch-head-acyclic"),
    (47, "reverse-list", "reverse-list", "( head -- new-head )", "reverse-linked-list", 4, "leetcode",
     "https://leetcode.com/problems/reverse-linked-list/", "linked-structure", "linked-cells", "Reverse Linked List",
     ("Reverse singly linked list; return new head index.", "In-place pointer reversal."),
     ("Iterative preferred.",),
     ("1 reverse-list -> 3", "ch-val@ 3 -> 2"),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 0 3 ch-val! 0 ch-next!\n1 constant ch-head"),
    (48, "middle-node", "middle-node", "( head -- idx )", "linked-list-middle", 4, "leetcode",
     "https://leetcode.com/problems/middle-of-the-linked-list/", "linked-structure", "linked-cells",
     "Middle of Linked List",
     ("Return index of middle node; for even length pick second middle.", "Fast/slow pointers."),
     ("Use index-based next pointers.",),
     ("1 middle-node -> 3",),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 4 3 ch-val! 4 ch-next!\n4 5 4 ch-val! 5 ch-next!\n5 0 5 ch-val! 0 ch-next!\n1 constant ch-head"),
    (49, "remove-nth-end", "remove-nth", "( head n -- new-head )", "remove-nth-from-end", 6, "leetcode",
     "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "linked-structure", "linked-cells",
     "Remove Nth From End",
     ("Remove nth node from end (1-indexed); return head.", "Use two-pass or two-pointer."),
     ("Mutates ch-next! fields.",),
     ("1 2 remove-nth -> 1", "1 1 remove-nth -> 2"),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 4 3 ch-val! 4 ch-next!\n4 0 4 ch-val! 0 ch-next!\n1 constant ch-head"),
    (50, "swap-pairs", "swap-pairs", "( head -- new-head )", "swap-nodes-in-pairs", 5, "leetcode",
     "https://leetcode.com/problems/swap-nodes-in-pairs/", "linked-structure", "linked-cells", "Swap Nodes in Pairs",
     ("Swap every two adjacent nodes; return new head.", "Odd tail unchanged."),
     ("Pointer surgery on indices.",),
     ("1 swap-pairs -> 2", "ch-val@ 2 -> 1"),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 4 3 ch-val! 4 ch-next!\n4 0 4 ch-val! 0 ch-next!\n1 constant ch-head"),
    (51, "add-two-numbers", "add-lists", "( ha hb -- hc )", "add-two-number-lists", 6, "leetcode",
     "https://leetcode.com/problems/add-two-numbers/", "linked-structure", "linked-cells", "Add Two Numbers",
     ("Add two digit lists (LSB first); return sum list head.", "Digits 0-9, no leading zeros except 0."),
     ("Propagate carry.",),
     ("1 2 add-lists -> 1", "ch-val@ 1 -> 7"),
     LINK + "\n2 3 1 ch-val! 2 ch-next!\n4 0 2 ch-val! 0 ch-next!\n5 6 3 ch-val! 4 ch-next!\n4 0 4 ch-val! 0 ch-next!\n1 constant ch-head-a\n3 constant ch-head-b"),
)

# trees-bst 52-59
extend(
    (52, "max-depth", "max-depth", "( root -- d )", "binary-tree-max-depth", 4, "leetcode",
     "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "trees-bst", "tree-cells", "Max Tree Depth",
     ("Return max depth of binary tree rooted at index root.", "Null child index is 0."),
     ("Recursive or BFS.", "Uses ch-t@ offsets val/left/right."),
     ("1 max-depth -> 3", "2 max-depth -> 2"),
     TREE + "\n3 0 ch-t!  2 1 ch-t!  3 2 ch-t!\n9 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n20 6 ch-t!  4 7 ch-t!  5 8 ch-t!\n15 9 ch-t!  0 10 ch-t!  0 11 ch-t!\n7 12 ch-t!  0 13 ch-t!  0 14 ch-t!\n1 constant ch-root\n2 constant ch-root-small"),
    (53, "min-depth", "min-depth", "( root -- d )", "binary-tree-min-depth", 5, "leetcode",
     "https://leetcode.com/problems/minimum-depth-of-binary-tree/", "trees-bst", "tree-cells", "Min Tree Depth",
     ("Return min root-to-leaf depth.", "Leaf has both children 0."),
     ("BFS preferred.", "Same tree scaffold."),
     ("1 min-depth -> 2"),
     TREE + "\n3 0 ch-t!  2 1 ch-t!  3 2 ch-t!\n9 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n20 6 ch-t!  4 7 ch-t!  5 8 ch-t!\n1 constant ch-root"),
    (54, "same-tree", "same-tree?", "( r1 r2 -- flag )", "same-binary-tree", 4, "leetcode",
     "https://leetcode.com/problems/same-tree/", "trees-bst", "tree-cells", "Same Tree",
     ("Return TRUE if trees at r1 and r2 are structurally identical with equal values."),
     ("Parallel recursion on indices.", "Return true/false."),
     ("1 1 same-tree? -> true", "1 2 same-tree? -> false"),
     TREE + "\n1 0 ch-t!  2 1 ch-t!  3 2 ch-t!\n1 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n1 6 ch-t!  2 7 ch-t!  1 8 ch-t!\n1 constant ch-root-a\n2 constant ch-root-b"),
    (55, "invert-tree", "invert-tree", "( root -- root )", "invert-binary-tree", 4, "leetcode",
     "https://leetcode.com/problems/invert-binary-tree/", "trees-bst", "tree-cells", "Invert Binary Tree",
     ("Swap left/right subtrees recursively in place.", "Return root unchanged."),
     ("Mutates ch-t! fields.", "Post-order swap."),
     ("1 invert-tree -> 1", "ch-t@ 1 -> 3", "ch-t@ 2 -> 2"),
     TREE + "\n4 0 ch-t!  2 1 ch-t!  7 2 ch-t!\n2 3 ch-t!  1 4 ch-t!  3 5 ch-t!\n5 6 ch-t!  6 7 ch-t!  4 8 ch-t!\n1 constant ch-root"),
    (56, "valid-bst", "valid-bst?", "( root -- flag )", "validate-binary-search-tree", 6, "leetcode",
     "https://leetcode.com/problems/validate-binary-search-tree/", "trees-bst", "tree-cells", "Validate BST",
     ("Return TRUE iff tree satisfies BST ordering.", "No duplicate values in tests."),
     ("Range check or inorder.", "Return true/false."),
     ("2 valid-bst? -> true", "1 valid-bst? -> false"),
     TREE + "\n2 0 ch-t!  1 1 ch-t!  3 2 ch-t!\n1 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n2 6 ch-t!  0 7 ch-t!  0 8 ch-t!\n2 constant ch-root-good\n5 9 ch-t!  1 10 ch-t!  4 11 ch-t!\n1 12 ch-t!  0 13 ch-t!  6 14 ch-t!\n3 15 ch-t!  0 16 ch-t!  0 17 ch-t!\n1 constant ch-root-bad"),
    (57, "kth-smallest", "kth-smallest", "( root k -- n )", "kth-smallest-bst", 6, "leetcode",
     "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "trees-bst", "tree-cells", "Kth Smallest BST",
     ("Return kth smallest value (1-indexed) in BST.", "Tree is valid BST."),
     ("Inorder walk counting nodes.", "Uses tree scaffold."),
     ("3 1 kth-smallest -> 1", "3 3 kth-smallest -> 3"),
     TREE + "\n3 0 ch-t!  1 1 ch-t!  4 2 ch-t!\n1 3 ch-t!  0 4 ch-t!  2 5 ch-t!\n2 6 ch-t!  0 7 ch-t!  0 8 ch-t!\n4 9 ch-t!  0 10 ch-t!  0 11 ch-t!\n3 constant ch-root"),
    (58, "path-sum", "path-sum?", "( root target -- flag )", "binary-tree-path-sum", 5, "leetcode",
     "https://leetcode.com/problems/path-sum/", "trees-bst", "tree-cells", "Path Sum",
     ("Return TRUE if root-to-leaf path sums to target.", "Leaf has no children."),
     ("DFS accumulation.", "Return true/false."),
     ("5 22 path-sum? -> true", "5 28 path-sum? -> false"),
     TREE + "\n5 0 ch-t!  4 1 ch-t!  8 2 ch-t!\n4 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n11 6 ch-t!  0 7 ch-t!  0 8 ch-t!\n4 9 ch-t!  0 10 ch-t!  0 11 ch-t!\n5 constant ch-root"),
    (59, "balanced-tree", "balanced?", "( root -- flag )", "balanced-binary-tree", 5, "leetcode",
     "https://leetcode.com/problems/balanced-binary-tree/", "trees-bst", "tree-cells", "Balanced Binary Tree",
     ("Return TRUE if heights of subtrees differ by at most 1 everywhere."),
     ("Post-order height check.", "Return true/false."),
     ("3 balanced? -> true", "1 balanced? -> false"),
     TREE + "\n3 0 ch-t!  2 1 ch-t!  3 2 ch-t!\n9 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n20 6 ch-t!  4 7 ch-t!  5 8 ch-t!\n1 constant ch-root\n1 9 ch-t!  2 10 ch-t!  2 11 ch-t!\n3 12 ch-t!  0 13 ch-t!  0 14 ch-t!\n3 15 ch-t!  0 16 ch-t!  0 17 ch-t!\n1 constant ch-root-unbal"),
)

# dynamic-programming 60-67
extend(
    (60, "max-subarray", "max-subarray", "( -- sum )", "maximum-subarray-kadane", 5, "leetcode",
     "https://leetcode.com/problems/maximum-subarray/", "dynamic-programming", "cell-array", "Maximum Subarray",
     ("Return maximum contiguous subarray sum in ch-data.", "At least one element."),
     ("Kadane algorithm.", "Uses ch-n preload."),
     ("max-subarray -> 6"),
     "-2 0 ch!  1 1 ch!  -3 2 ch!  4 3 ch!  -1 4 ch!  2 5 ch!  1 6 ch!  -5 7 ch!\n8 constant ch-n"),
    (61, "climb-stairs", "climb", "( n -- ways )", "climbing-stairs-count", 4, "leetcode",
     "https://leetcode.com/problems/climbing-stairs/", "dynamic-programming", "scalar", "Climbing Stairs",
     ("Return number of distinct ways to climb n steps taking 1 or 2.", "n<=20 in tests."),
     ("Fibonacci DP.", "Iterative."),
     ("2 climb -> 2", "3 climb -> 3", "5 climb -> 8", "1 climb -> 1")),
    (62, "unique-paths", "unique-paths", "( m n -- count )", "unique-paths-grid", 5, "leetcode",
     "https://leetcode.com/problems/unique-paths/", "dynamic-programming", "scalar", "Unique Paths",
     ("Return paths from top-left to bottom-right moving only right/down in m x n grid."),
     ("Combinatorics or DP table.", "m,n positive."),
     ("3 2 unique-paths -> 3", "3 7 unique-paths -> 28", "1 1 unique-paths -> 1")),
    (63, "min-path-sum", "min-path-sum", "( -- sum )", "minimum-path-sum-grid", 6, "leetcode",
     "https://leetcode.com/problems/minimum-path-sum/", "dynamic-programming", "grid", "Minimum Path Sum",
     ("Return min sum path from top-left to bottom-right using ch-grid.", "Only right/down moves."),
     ("DP on grid scaffold.", "Uses preloaded costs."),
     ("min-path-sum -> 7"),
     "1 0 0 ch-grid!  3 1 0 ch-grid!  1 2 0 ch-grid!\n1 0 1 ch-grid!  5 1 1 ch-grid!  1 2 1 ch-grid!\n4 0 2 ch-grid!  2 1 2 ch-grid!  1 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (64, "max-prod-sub", "max-prod-sub", "( -- prod )", "maximum-product-subarray", 6, "leetcode",
     "https://leetcode.com/problems/maximum-product-subarray/", "dynamic-programming", "cell-array",
     "Maximum Product Subarray",
     ("Return maximum product of contiguous subarray in ch-data."),
     ("Track min and max DP.", "Handles negatives."),
     ("max-prod-sub -> 6"),
     "2 0 ch!  3 1 ch!  -2 2 ch!  4 3 ch!\n4 constant ch-n"),
    (65, "coin-change", "coin-change", "( amount -- ways )", "coin-change-combinations", 6, "leetcode",
     "https://leetcode.com/problems/coin-change/", "dynamic-programming", "cell-array", "Coin Change Ways",
     ("Count ways to make amount using coins in ch-data[0..ch-n).", "Unlimited coin supply."),
     ("Unbounded knapsack DP.", "amount on stack."),
     ("5 coin-change -> 4", "3 coin-change -> 0"),
     "1 0 ch!  2 1 ch!  5 2 ch!\n3 constant ch-n"),
    (66, "word-break", "word-break?", "( c-addr u -- flag )", "word-break-dictionary", 6, "leetcode",
     "https://leetcode.com/problems/word-break/", "dynamic-programming", "string", "Word Break",
     ("Return TRUE if string can be segmented into space-separated dictionary words.", "Dictionary in ch-dict helper."),
     ("DP over positions.", "Use ch-setup."),
     ('s"leetcode" ch-setup word-break? -> true', 's"applepen" ch-setup word-break? -> true',
      's"catsandog" ch-setup word-break? -> false'),
     'create ch-dict\ns" leet code apple pen" ch-setup drop'),
    (67, "lis-length", "lis-len", "( -- len )", "longest-increasing-subsequence", 7, "leetcode",
     "https://leetcode.com/problems/longest-increasing-subsequence/", "dynamic-programming", "cell-array",
     "Longest Increasing Subsequence",
     ("Return length of longest strictly increasing subsequence in ch-data."),
     ("O(n^2) DP OK for small n.", "Uses ch-n."),
     ("lis-len -> 4"),
     "10 0 ch!  9 1 ch!  2 2 ch!  5 3 ch!  3 4 ch!  7 5 ch!  101 6 ch!  18 7 ch!\n8 constant ch-n"),
)

# graph 68-74
extend(
    (68, "num-islands", "num-islands", "( -- count )", "count-islands-grid", 6, "leetcode",
     "https://leetcode.com/problems/number-of-islands/", "graph", "grid", "Number of Islands",
     ("Count connected components of 1-cells in ch-grid (4-directional).", "0=water 1=land."),
     ("DFS/BFS flood fill.", "Uses ch-grid@."),
     ("num-islands -> 1"),
     "1 0 0 ch-grid!  1 1 0 ch-grid!  0 2 0 ch-grid!\n0 0 1 ch-grid!  0 1 1 ch-grid!  0 2 1 ch-grid!\n0 0 2 ch-grid!  0 1 2 ch-grid!  0 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (69, "can-finish", "can-finish?", "( -- flag )", "course-schedule-topo", 6, "leetcode",
     "https://leetcode.com/problems/course-schedule/", "graph", "cell-array", "Course Schedule",
     ("Return TRUE if all courses can finish given prereq pairs in ch-edges.", "No cycle in directed graph."),
     ("Topological sort.", "Preload edges as flat pairs."),
     ("can-finish? -> true"),
     "2 0 ch!  0 1 ch!  1 1 ch!\n2 constant ch-n\n2 constant ch-num-courses"),
    (70, "shortest-path", "shortest-path", "( -- len )", "shortest-path-binary-matrix", 6, "leetcode",
     "https://leetcode.com/problems/shortest-path-in-binary-matrix/", "graph", "grid", "Shortest Path Binary",
     ("Return shortest path length from top-left to bottom-right through 0-cells.", "Return 0 if blocked."),
     ("BFS on grid.", "8-directional or 4-directional per spec: use 8."),
     ("shortest-path -> 2"),
     "0 0 0 ch-grid!  1 1 0 ch-grid!\n1 0 1 ch-grid!  0 1 1 ch-grid!\n2 constant ch-cols-used\n2 constant ch-rows-used"),
    (71, "rotting-oranges", "rotten-days", "( -- days )", "rotting-oranges-bfs", 6, "leetcode",
     "https://leetcode.com/problems/rotting-oranges/", "graph", "grid", "Rotting Oranges",
     ("Return minutes until no fresh orange remains; -1 if impossible.", "2=rotten 1=fresh 0=empty."),
     ("Multi-source BFS.", "Uses grid scaffold."),
     ("rotten-days -> 4"),
     "2 0 0 ch-grid!  1 1 0 ch-grid!  1 2 0 ch-grid!\n1 0 1 ch-grid!  0 1 1 ch-grid!  2 2 1 ch-grid!\n2 0 2 ch-grid!  1 1 2 ch-grid!  1 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (72, "word-ladder-len", "ladder-len", "( -- len )", "word-ladder-length", 9, "leetcode",
     "https://leetcode.com/problems/word-ladder/", "graph", "string", "Word Ladder Length",
     ("Return shortest transformation length from ch-start to ch-end using ch-wordlist.", "One letter change per step."),
     ("BFS on implicit graph.", "Preload start/end strings."),
     ("ladder-len -> 5"),
     's" hit" ch-setup drop constant ch-start\ns" cog" ch-setup drop constant ch-end\ns" hot dot dog lot log cog" ch-setup drop'),
    (73, "surrounded-regions", "capture-count", "( -- count )", "surrounded-regions-flip", 7, "leetcode",
     "https://leetcode.com/problems/surrounded-regions/", "graph", "grid", "Surrounded Regions",
     ("Return count of O regions fully surrounded by X after capture.", "X and O on grid."),
     ("DFS from borders.", "Mutates grid to count."),
     ("capture-count -> 1"),
     "X 0 0 ch-grid!  X 1 0 ch-grid!  X 2 0 ch-grid!\nX 0 1 ch-grid!  O 1 1 ch-grid!  X 2 1 ch-grid!\nX 0 2 ch-grid!  X 1 2 ch-grid!  X 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (74, "pe-multiples", "pe-mult3-5", "( limit -- sum )", "project-euler-multiples", 3, "project-euler",
     "https://projecteuler.net/problem=1", "graph", "scalar", "PE Multiples of 3 and 5",
     ("Return sum of natural numbers below limit divisible by 3 or 5.", "Classic Project Euler #1."),
     ("Inclusion-exclusion or simple loop.", "limit on stack."),
     ("10 pe-mult3-5 -> 23", "1000 pe-mult3-5 -> 233168", "15 pe-mult3-5 -> 45")),
)

# greedy 75-81
extend(
    (75, "jump-game", "jump-ok?", "( -- flag )", "jump-game-reachable", 5, "leetcode",
     "https://leetcode.com/problems/jump-game/", "greedy", "cell-array", "Jump Game",
     ("Return TRUE if last index reachable from index 0 by jumps <= ch-data[i]."),
     ("Greedy farthest reach.", "Return true/false."),
     ("jump-ok? -> true"),
     "2 0 ch!  3 1 ch!  1 2 ch!  1 3 ch!  4 4 ch!\n5 constant ch-n"),
    (76, "jump-min", "jump-min", "( -- steps )", "jump-game-minimum", 6, "leetcode",
     "https://leetcode.com/problems/jump-game-ii/", "greedy", "cell-array", "Jump Game II",
     ("Return minimum jumps to reach last index.", "Always reachable in tests."),
     ("Greedy BFS layers.", "Uses ch-n."),
     ("jump-min -> 2"),
     "2 0 ch!  3 1 ch!  1 2 ch!  1 3 ch!  4 4 ch!\n5 constant ch-n"),
    (77, "max-profit", "max-profit", "( -- profit )", "best-time-buy-sell-stock", 4, "leetcode",
     "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "greedy", "cell-array", "Best Time Stock",
     ("Return max profit from one buy/sell using daily prices in ch-data.", "Must buy before sell."),
     ("Track min price so far.", "Single pass."),
     ("max-profit -> 5"),
     "7 0 ch!  1 1 ch!  5 2 ch!  3 3 ch!  6 4 ch!  4 5 ch!\n6 constant ch-n"),
    (78, "gas-station", "gas-start", "( -- idx )", "gas-station-circuit", 6, "leetcode",
     "https://leetcode.com/problems/gas-station/", "greedy", "cell-array", "Gas Station",
     ("Return starting station index for circuit or -1.", "gas and cost arrays interleaved in ch-data."),
     ("Single pass greedy.", "Preload gas/cost pairs."),
     ("gas-start -> 3"),
     "1 0 ch!  2 1 ch!  3 2 ch!  4 3 ch!  5 4 ch!  1 5 ch!  2 6 ch!  3 7 ch!  4 8 ch!  5 9 ch!\n10 constant ch-n"),
    (79, "candy", "candy-min", "( -- total )", "candy-distribution", 6, "leetcode",
     "https://leetcode.com/problems/candy/", "greedy", "cell-array", "Candy",
     ("Return minimum candies for ch-data ratings (neighbors compare)."),
     ("Two-pass greedy.", "Uses ch-n."),
     ("candy-min -> 5"),
     "1 0 ch!  0 1 ch!  2 2 ch!\n3 constant ch-n"),
    (80, "assign-cookies", "assign-cookies", "( -- count )", "assign-cookies-greedy", 4, "leetcode",
     "https://leetcode.com/problems/assign-cookies/", "greedy", "cell-array", "Assign Cookies",
     ("Maximize children content with cookie sizes; ch-g and ch-s segments preloaded."),
     ("Sort and two-pointer.", "Return count satisfied."),
     ("assign-cookies -> 2"),
     "1 0 ch!  2 1 ch!  3 2 ch!\n1 3 ch!  1 4 ch!\n5 constant ch-n\n3 constant ch-g-len"),
    (81, "partition-labels", "part-labels-len", "( c-addr u -- len )", "partition-labels-count", 5, "leetcode",
     "https://leetcode.com/problems/partition-labels/", "greedy", "string", "Partition Labels",
     ("Return count of partition sizes as single number for benchmark (product or sum per spec: return part count).",
      "Return number of parts needed."),
     ("Greedy last occurrence.", "Use ch-setup."),
     ('s" ababcbacadefegdehijhklij" ch-setup part-labels-len -> 3',
      's" eccbbbbdec" ch-setup part-labels-len -> 2')),
)

# heap-topk 82-87
extend(
    (82, "kth-largest", "kth-largest", "( k -- n )", "kth-largest-element", 5, "leetcode",
     "https://leetcode.com/problems/kth-largest-element-in-an-array/", "heap-topk", "cell-array", "Kth Largest",
     ("Return kth largest element in unsorted ch-data.", "1-indexed k."),
     ("Quickselect or heap.", "Uses ch-n preload."),
     ("2 kth-largest -> 5", "4 kth-largest -> 4"),
     "3 0 ch!  2 1 ch!  1 2 ch!  5 3 ch!  6 4 ch!  4 5 ch!\n6 constant ch-n"),
    (83, "top-k-frequent", "top-k-freq", "( k -- n )", "top-k-frequent-element", 6, "leetcode",
     "https://leetcode.com/problems/top-k-frequent-elements/", "heap-topk", "cell-array", "Top K Frequent",
     ("Return most frequent element among top-k (benchmark returns single mode for k=1)."),
     ("Count then select.", "k on stack."),
     ("1 top-k-freq -> 1"),
     "1 0 ch!  1 1 ch!  1 2 ch!  2 3 ch!  2 4 ch!  2 5 ch!\n6 constant ch-n"),
    (84, "merge-k-lists", "merge-k", "( -- head )", "merge-k-sorted-lists", 9, "leetcode",
     "https://leetcode.com/problems/merge-k-sorted-lists/", "heap-topk", "linked-cells", "Merge K Lists",
     ("Merge k sorted lists whose heads are in ch-heads array; return merged head."),
     ("Heap or divide-conquer.", "Preload list heads."),
     ("merge-k -> 1"),
     LINK + "\n1 2 1 ch-val! 1 ch-next!\n3 0 2 ch-val! 0 ch-next!\n2 4 3 ch-val! 3 ch-next!\n4 0 4 ch-val! 0 ch-next!\n1 0 ch!  3 1 ch!\n2 constant ch-k\n2 constant ch-n"),
    (85, "k-closest", "k-closest", "( k -- dist )", "k-closest-points-origin", 6, "leetcode",
     "https://leetcode.com/problems/k-closest-points-to-origin/", "heap-topk", "cell-array", "K Closest Points",
     ("Return squared distance of kth closest point to origin from ch-pairs x,y interleaved."),
     ("Partial sort or heap.", "k on stack."),
     ("1 k-closest -> 2", "2 k-closest -> 5"),
     "1 0 ch!  3 1 ch!  -2 2 ch!  2 3 ch!\n4 constant ch-n"),
    (86, "find-k-pairs", "k-pairs-sum", "( k -- sum )", "find-k-pairs-with-smallest-sums", 7, "leetcode",
     "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/", "heap-topk", "cell-array", "K Pairs Smallest",
     ("Return sum of kth smallest pair from two sorted arrays in ch-a/ch-b segments."),
     ("Heap merge.", "Preload arrays."),
     ("2 k-pairs-sum -> 4"),
     "1 0 ch!  7 1 ch!  2 2 ch!  4 3 ch!  6 4 ch!\n3 0 ch!  1 1 ch!  3 2 ch!\n5 constant ch-n\n3 constant ch-a-len"),
    (87, "last-stone", "last-stone", "( -- n )", "last-stone-weight", 5, "codewars",
     "https://www.codewars.com/kata/last-stone-weight", "heap-topk", "cell-array", "Last Stone Weight",
     ("Repeatedly smash two largest stones; return last weight or 0.", "Use ch-data as heap array."),
     ("Simulate with sorted pass.", "Preload stones."),
     ("last-stone -> 1"),
     "2 0 ch!  7 1 ch!  4 3 ch!  1 4 ch!  8 5 ch!\n6 constant ch-n"),
)

# matrix 88-94
extend(
    (88, "valid-sudoku", "sudoku?", "( -- flag )", "valid-sudoku-board", 6, "leetcode",
     "https://leetcode.com/problems/valid-sudoku/", "matrix", "grid", "Valid Sudoku",
     ("Return TRUE if 9x9 partial sudoku has no row/col/box duplicates.", "0=empty digit."),
     ("Use bitmask or hash.", "Preload board digits."),
     ("sudoku? -> true"),
     "5 0 0 ch-grid!  3 1 0 ch-grid!  0 2 0 ch-grid!  0 3 0 ch-grid!  7 4 0 ch-grid!  0 5 0 ch-grid!  0 6 0 ch-grid!  0 7 0 ch-grid!  0 8 0 ch-grid!\n6 0 1 ch-grid!  0 1 1 ch-grid!  0 2 1 ch-grid!  1 3 1 ch-grid!  9 4 1 ch-grid!  5 5 1 ch-grid!  0 6 1 ch-grid!  0 7 1 ch-grid!  0 8 1 ch-grid!\n0 0 2 ch-grid!  9 1 2 ch-grid!  8 2 2 ch-grid!  0 3 2 ch-grid!  0 4 2 ch-grid!  0 5 2 ch-grid!  0 6 2 ch-grid!  6 7 2 ch-grid!  0 8 2 ch-grid!\n9 constant ch-cols-used\n9 constant ch-rows-used"),
    (89, "rotate-matrix", "rotate-90", "( -- )", "rotate-image-90", 6, "leetcode",
     "https://leetcode.com/problems/rotate-image/", "matrix", "grid", "Rotate Image",
     ("Rotate ch-grid square matrix 90 degrees clockwise in place.", "n x n preloaded."),
     ("Layer swap or transpose+reverse.", "Mutates grid."),
     ("rotate-90", "ch-grid@ 0 0 -> 4", "ch-grid@ 0 2 -> 1"),
     "1 0 0 ch-grid!  2 1 0 ch-grid!  3 2 0 ch-grid!\n4 0 1 ch-grid!  5 1 1 ch-grid!  6 2 1 ch-grid!\n7 0 2 ch-grid!  8 1 2 ch-grid!  9 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (90, "spiral-len", "spiral-cells", "( -- count )", "spiral-matrix-count", 5, "leetcode",
     "https://leetcode.com/problems/spiral-matrix/", "matrix", "grid", "Spiral Matrix Count",
     ("Return number of cells visited in clockwise spiral order (benchmark counts visits)."),
     ("Simulate directions.", "Uses rectangular grid."),
     ("spiral-cells -> 9"),
     "1 0 0 ch-grid!  2 1 0 ch-grid!  3 2 0 ch-grid!\n4 0 1 ch-grid!  5 1 1 ch-grid!  6 2 1 ch-grid!\n7 0 2 ch-grid!  8 1 2 ch-grid!  9 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (91, "set-zeroes", "set-zeroes", "( -- )", "set-matrix-zeroes", 6, "leetcode",
     "https://leetcode.com/problems/set-matrix-zeroes/", "matrix", "grid", "Set Matrix Zeroes",
     ("Zero entire row and column if cell is 0.", "In-place marker trick allowed."),
     ("Mutates ch-grid.", "Preload matrix."),
     ("set-zeroes", "ch-grid@ 0 0 -> 0", "ch-grid@ 1 1 -> 0"),
     "0 0 0 ch-grid!  1 1 0 ch-grid!  1 2 0 ch-grid!\n1 0 1 ch-grid!  0 1 1 ch-grid!  1 2 1 ch-grid!\n3 constant ch-cols-used\n2 constant ch-rows-used"),
    (92, "game-of-life", "life-next", "( -- )", "game-of-life-next", 7, "leetcode",
     "https://leetcode.com/problems/game-of-life/", "matrix", "grid", "Game of Life",
     ("Apply Conway rules to ch-grid in place for one generation.", "1=live 0=dead."),
     ("Use scratch or in-place encoding.", "Mutates grid."),
     ("life-next", "ch-grid@ 1 1 -> 1"),
     "0 0 0 ch-grid!  1 1 0 ch-grid!  0 2 0 ch-grid!\n0 0 1 ch-grid!  0 1 1 ch-grid!  1 2 1 ch-grid!\n0 0 2 ch-grid!  1 1 2 ch-grid!  0 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (93, "word-search", "word-search?", "( c-addr u -- flag )", "word-search-grid", 7, "leetcode",
     "https://leetcode.com/problems/word-search/", "matrix", "grid", "Word Search",
     ("Return TRUE if word exists in ch-grid using adjacent cell path.", "Reuse cell allowed per path."),
     ("Backtracking DFS.", "Use ch-setup for word."),
     ('s" ABCCED" ch-setup word-search? -> true', 's" SEE" ch-setup word-search? -> true',
      's" ABCB" ch-setup word-search? -> false'),
     "A 0 0 ch-grid!  B 1 0 ch-grid!  C 2 0 ch-grid!\nB 0 1 ch-grid!  E 1 1 ch-grid!  C 2 1 ch-grid!\nA 0 2 ch-grid!  D 1 2 ch-grid!  E 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
    (94, "max-area-island", "max-island", "( -- area )", "max-area-of-island", 6, "leetcode",
     "https://leetcode.com/problems/max-area-of-island/", "matrix", "grid", "Max Area Island",
     ("Return area of largest 1-component in ch-grid."),
     ("DFS count.", "Uses grid scaffold."),
     ("max-island -> 6"),
     "0 0 0 ch-grid!  0 1 0 ch-grid!  1 2 0 ch-grid!\n0 0 1 ch-grid!  0 1 1 ch-grid!  0 2 1 ch-grid!\n1 0 2 ch-grid!  1 1 2 ch-grid!  1 2 2 ch-grid!\n3 constant ch-cols-used\n3 constant ch-rows-used"),
)

# sliding-window 95-100
extend(
    (95, "longest-unique", "longest-unique", "( c-addr u -- len )", "longest-substring-without-repeating", 5,
     "leetcode", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "sliding-window",
     "string", "Longest Unique Substring",
     ("Return length of longest substring without repeating characters."),
     ("Sliding window with map.", "Use ch-setup."),
     ('s" abcabcbb" ch-setup longest-unique -> 3', 's" bbbbb" ch-setup longest-unique -> 1',
      's" pwwkew" ch-setup longest-unique -> 3', 's" " ch-setup longest-unique -> 0')),
    (96, "min-window-len", "min-window", "( s-addr su t-addr tu -- len )", "minimum-window-substring", 9,
     "leetcode", "https://leetcode.com/problems/minimum-window-substring/", "sliding-window", "string",
     "Minimum Window Substring",
     ("Return length of smallest window in s containing all chars of t.", "Return 0 if none."),
     ("Sliding window with counts.", "Both strings via ch-setup."),
     ('s" ADOBECODEBANC" ch-setup s" ABC" ch-setup min-window -> 4',
      's" a" ch-setup s" a" ch-setup min-window -> 1',
      's" a" ch-setup s" aa" ch-setup min-window -> 0')),
    (97, "max-consecutive-ones", "max-ones", "( k -- len )", "max-consecutive-ones-iii", 5, "leetcode",
     "https://leetcode.com/problems/max-consecutive-ones-iii/", "sliding-window", "cell-array",
     "Max Consecutive Ones",
     ("Return longest subarray of 1s after flipping at most k zeros in ch-data."),
     ("Sliding window.", "k on stack."),
     ("1 max-ones -> 6", "2 max-ones -> 10"),
     "1 0 ch!  1 1 ch!  0 2 ch!  1 3 ch!  1 4 ch!  0 5 ch!  1 6 ch!  1 7 ch!  1 8 ch!  0 9 ch!\n10 constant ch-n"),
    (98, "fruit-baskets", "fruit-baskets", "( -- len )", "fruit-into-baskets", 5, "leetcode",
     "https://leetcode.com/problems/fruit-into-baskets/", "sliding-window", "cell-array", "Fruit Into Baskets",
     ("Return longest subarray with at most 2 distinct values in ch-data."),
     ("Sliding window.", "Uses ch-n."),
     ("fruit-baskets -> 3"),
     "1 0 ch!  2 1 ch!  1 2 ch!  2 3 ch!  3 4 ch!\n5 constant ch-n"),
    (99, "subarray-product", "subarray-prod", "( k -- count )", "subarray-product-less-than-k", 6, "leetcode",
     "https://leetcode.com/problems/subarray-product-less-than-k/", "sliding-window", "cell-array",
     "Subarray Product Less Than K",
     ("Count contiguous subarrays with product strictly less than k."),
     ("Sliding window on positives.", "k on stack."),
     ("100 subarray-prod -> 8", "0 subarray-prod -> 0"),
     "10 0 ch!  5 1 ch!  2 2 ch!  6 3 ch!\n4 constant ch-n"),
    (100, "max-vowels", "max-vowels", "( k -- len )", "maximum-vowels-substring", 4, "leetcode",
     "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/",
     "sliding-window", "string", "Maximum Vowels Substring",
     ("Return max vowels in any length-k substring of preloaded string ch-text."),
     ("Fixed-size sliding window.", "k on stack."),
     ("3 max-vowels -> 3", "2 max-vowels -> 2"),
     's" abciiidef" ch-setup drop\n9 constant ch-text-len'),
)

# bit-xor 101-106
extend(
    (101, "single-number", "single", "( a b c -- n )", "single-number-xor", 3, "leetcode",
     "https://leetcode.com/problems/single-number/", "bit-xor", "scalar", "Single Number",
     ("Return element that appears once when others appear twice.", "Three values on stack for benchmark."),
     ("XOR all values.", "Scalar demo of pattern."),
     ("2 2 1 single -> 1", "4 1 4 single -> 1", "7 3 3 single -> 7")),
    (102, "single-number-ii", "single-ii", "( -- n )", "single-number-appears-thrice", 6, "leetcode",
     "https://leetcode.com/problems/single-number-ii/", "bit-xor", "cell-array", "Single Number II",
     ("Return element appearing once while others appear three times."),
     ("Bit count per bit position.", "Uses ch-data preload."),
     ("single-ii -> 3"),
     "2 0 ch!  2 1 ch!  3 2 ch!  2 3 ch!\n4 constant ch-n"),
    (103, "count-bits", "count-bits", "( n -- c )", "counting-bits-popcount", 4, "leetcode",
     "https://leetcode.com/problems/counting-bits/", "bit-xor", "scalar", "Counting Bits",
     ("Return number of 1-bits in binary representation of n."),
     ("Brian Kernighan or lookup.", "Non-negative n."),
     ("0 count-bits -> 0", "1 count-bits -> 1", "5 count-bits -> 2", "7 count-bits -> 3", "15 count-bits -> 4")),
    (104, "reverse-bits", "reverse-bits", "( n -- r )", "reverse-bits-32", 5, "leetcode",
     "https://leetcode.com/problems/reverse-bits/", "bit-xor", "scalar", "Reverse Bits",
     ("Reverse low 8 bits of n for benchmark (8-bit variant).", "Higher bits zero."),
     ("Bit iteration.", "8-bit test scope."),
     ("240 reverse-bits -> 15", "1 reverse-bits -> 128", "255 reverse-bits -> 255")),
    (105, "divide-int", "divide-int", "( a b -- q )", "divide-two-integers", 6, "leetcode",
     "https://leetcode.com/problems/divide-two-integers/", "bit-xor", "scalar", "Divide Two Integers",
     ("Return a/b truncated toward zero without using / or mod.", "Assume b!=0."),
     ("Bit shift subtract.", "Handle signs."),
     ("10 3 divide-int -> 3", "-10 3 divide-int -> -3", "7 2 divide-int -> 3", "0 5 divide-int -> 0")),
    (106, "hamming-weight", "hamming", "( n -- w )", "hamming-weight-popcount", 3, "rosetta",
     "https://rosettacode.org/wiki/Hamming_weight", "bit-xor", "scalar", "Hamming Weight",
     ("Return count of set bits (same as popcount).", "Rosetta variant name."),
     ("Use bit operations.", "Non-negative."),
    ("0 hamming -> 0", "106 hamming -> 4", "255 hamming -> 8", "13 hamming -> 3")),
)

# trie-design 107-111
extend(
    (107, "trie-insert", "trie-insert", "( c-addr u -- )", "implement-trie-insert", 6, "leetcode",
     "https://leetcode.com/problems/implement-trie-prefix-tree/", "trie-design", "string", "Trie Insert",
     ("Insert counted string into internal trie.", "Companion trie-search? returns flag."),
     ("Node array trie.", "Use ch-setup in tests."),
     ('s" apple" ch-setup trie-insert s" apple" ch-setup trie-search? -> true',
      's" app" ch-setup trie-search? -> false')),
    (108, "trie-starts", "trie-starts?", "( c-addr u -- flag )", "trie-starts-with", 5, "leetcode",
     "https://leetcode.com/problems/implement-trie-prefix-tree/", "trie-design", "string", "Trie Starts With",
     ("Return TRUE if any inserted key has given prefix.", "Requires prior inserts in test."),
     ("Prefix walk.", "Use ch-setup."),
     ('s" app" ch-setup trie-starts? -> true', 's" b" ch-setup trie-starts? -> false'),
     's" apple" ch-setup trie-insert drop'),
    (109, "word-dict", "word-dict?", "( c-addr u -- flag )", "add-and-search-word-dictionary", 6, "leetcode",
     "https://leetcode.com/problems/add-and-search-word-data-structure-design/", "trie-design", "string",
     "Word Dictionary",
     ("Return TRUE if word exists allowing '.' wildcard.", "Trie with wildcard search."),
     ("DFS on trie.", "Preload dictionary."),
     ('s" bad" ch-setup word-dict? -> true', 's" b.d" ch-setup word-dict? -> true',
      's" b.dz" ch-setup word-dict? -> false'),
     's" bad" ch-setup dict-add drop\ns" dad" ch-setup dict-add drop\ns" mad" ch-setup dict-add drop'),
    (110, "prefix-suffix", "prefix-suffix?", "( c-addr u -- flag )", "prefix-and-suffix-search", 7, "leetcode",
     "https://leetcode.com/problems/prefix-and-suffix-search/", "trie-design", "string", "Prefix Suffix Search",
     ("Return TRUE if any word has given prefix and suffix simultaneously.", "Benchmark boolean variant."),
     ("Combined trie or hash.", "Use ch-setup."),
     ('s" apple" ch-setup prefix-suffix? -> true', 's" xyz" ch-setup prefix-suffix? -> false'),
     's" apple" ch-setup dict-add drop'),
    (111, "longest-dict-word", "longest-dict", "( c-addr u -- len )", "longest-word-in-dictionary", 5, "leetcode",
     "https://leetcode.com/problems/longest-word-in-dictionary/", "trie-design", "string", "Longest Dictionary Word",
     ("Return length of longest word from dictionary buildable by adding one char at a time."),
     ("Trie + BFS/DFS.", "Dictionary preloaded."),
     ('s" w" ch-setup longest-dict -> 3'),
     's" w" ch-setup dict-add drop\ns" wo" ch-setup dict-add drop\ns" wor" ch-setup dict-add drop\ns" worl" ch-setup dict-add drop\ns" world" ch-setup dict-add drop'),
)

# parse-interpreter 112-116
extend(
    (112, "calc-basic", "calc-basic", "( c-addr u -- n )", "basic-calculator-ii", 6, "leetcode",
     "https://leetcode.com/problems/basic-calculator-ii/", "parse-interpreter", "string", "Basic Calculator II",
     ("Evaluate string expression with + - * / on non-negative integers.", "Spaces optional."),
     ("Stack or linear scan.", "Use ch-setup."),
     ('s" 3+2*2" ch-setup calc-basic -> 7', 's" 3/2" ch-setup calc-basic -> 1',
      's" 2+3*4" ch-setup calc-basic -> 14')),
    (113, "score-parens", "score-parens", "( c-addr u -- n )", "score-of-parentheses", 5, "leetcode",
     "https://leetcode.com/problems/score-of-parentheses/", "parse-interpreter", "string", "Score of Parentheses",
     ("Return score: ()=1, AB=A+B, (A)=2*A for balanced parens only.", "Differs from validation seed."),
     ("Stack accumulation.", "Use ch-setup."),
     ('s" ()" ch-setup score-parens -> 1', 's" (())" ch-setup score-parens -> 2',
      's" ()()" ch-setup score-parens -> 2', 's" (()(()))" ch-setup score-parens -> 6')),
    (114, "parse-int-hex", "parse-hex", "( c-addr u -- n )", "parse-hex-literal", 5, "kata",
     "https://www.codewars.com/kata/hex-to-decimal", "parse-interpreter", "string", "Parse Hex",
     ("Parse 0x-prefixed or plain hex string to integer.", "Lowercase hex digits."),
     ("Digit parser loop.", "Use ch-setup."),
     ('s" ff" ch-setup parse-hex -> 255', 's" 2a" ch-setup parse-hex -> 42',
      's" 0" ch-setup parse-hex -> 0')),
    (115, "atom-count", "atom-count", "( c-addr u -- n )", "number-of-atoms-count", 7, "leetcode",
     "https://leetcode.com/problems/number-of-atoms/", "parse-interpreter", "string", "Number of Atoms Count",
     ("Return total atom count from chemical formula (uppercase element + optional digits).", "Simplified: count letters+digits."),
     ("Stack parser.", "Use ch-setup."),
     ('s" H2O" ch-setup atom-count -> 3', 's" Mg(OH)2" ch-setup atom-count -> 6',
      's" K4(ON(SO3)2)2" ch-setup atom-count -> 18')),
    (116, "fizzbuzz-count", "fizzbuzz-n", "( n -- count )", "fizzbuzz-line-count", 2, "rosetta",
     "https://rosettacode.org/wiki/FizzBuzz", "parse-interpreter", "scalar", "FizzBuzz Count",
     ("Return count of numbers 1..n matching fizz OR buzz (not both double-count).", "Benchmark returns match count."),
     ("Simple loop.", "n on stack."),
     ("15 fizzbuzz-n -> 7", "30 fizzbuzz-n -> 14", "1 fizzbuzz-n -> 0")),
)

# recursion 117-123
extend(
    (117, "gen-parens-count", "gen-parens-n", "( n -- count )", "generate-parentheses-count", 5, "leetcode",
     "https://leetcode.com/problems/generate-parentheses/", "recursion", "scalar", "Generate Parentheses Count",
     ("Return number of valid combinations of n pairs of parentheses.", "Catalan number."),
     ("Recursion or DP count only.", "Do not enumerate strings."),
     ("1 gen-parens-n -> 1", "2 gen-parens-n -> 2", "3 gen-parens-n -> 5", "4 gen-parens-n -> 14")),
    (118, "phone-combos", "phone-combos", "( d -- count )", "letter-combinations-count", 4, "leetcode",
     "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", "recursion", "scalar",
     "Phone Letter Combos Count",
     ("Return count of letter combinations for phone digit d (2-9).", "Benchmark scalar: 3->3 letters etc."),
     ("Recursion count.", "Single digit on stack."),
     ("2 phone-combos -> 3", "7 phone-combos -> 4", "9 phone-combos -> 4", "0 phone-combos -> 0")),
    (119, "combo-sum", "combo-sum?", "( target -- flag )", "combination-sum-exists", 6, "leetcode",
     "https://leetcode.com/problems/combination-sum/", "recursion", "cell-array", "Combination Sum Exists",
     ("Return TRUE if some multiset from ch-data sums to target.", "Reuse elements allowed."),
     ("Backtracking.", "Uses preloaded candidates."),
     ("7 combo-sum? -> true", "2 combo-sum? -> false"),
     "2 0 ch!  3 1 ch!  6 2 ch!  7 3 ch!\n4 constant ch-n"),
    (120, "permute-count", "permute-n", "( n -- count )", "permutations-count", 5, "leetcode",
     "https://leetcode.com/problems/permutations/", "recursion", "scalar", "Permutations Count",
     ("Return n! for n distinct items.", "Benchmark uses factorial count."),
     ("Recursive multiply.", "n<=10 in tests."),
     ("0 permute-n -> 1", "1 permute-n -> 1", "3 permute-n -> 6", "4 permute-n -> 24", "5 permute-n -> 120")),
    (121, "subsets-count", "subsets-n", "( n -- count )", "subsets-count", 4, "leetcode",
     "https://leetcode.com/problems/subsets/", "recursion", "scalar", "Subsets Count",
     ("Return 2^n count of subsets of n elements.", "n<=10."),
     ("Bit shift or recursion.", "Power of two."),
     ("0 subsets-n -> 1", "1 subsets-n -> 2", "3 subsets-n -> 8", "10 subsets-n -> 1024")),
    (122, "hanoi-moves", "hanoi", "( n -- moves )", "tower-of-hanoi-moves", 4, "rosetta",
     "https://rosettacode.org/wiki/Tower_of_Hanoi", "recursion", "scalar", "Tower of Hanoi",
     ("Return minimum moves to solve n-disk Tower of Hanoi.", "Classic recurrence 2^n-1."),
     ("Recursive formula.", "n>=0."),
     ("0 hanoi -> 0", "1 hanoi -> 1", "3 hanoi -> 7", "4 hanoi -> 15", "10 hanoi -> 1023")),
    (123, "quick-exponent", "power-rec", "( base exp -- n )", "recursive-power", 5, "codewars",
     "https://www.codewars.com/kata/recursive-exponentiation", "recursion", "scalar", "Recursive Power",
     ("Compute base^exp recursively for non-negative exp.", "Distinct from iterative ipow."),
     ("Recursive divide.", "exp fits cell."),
     ("2 10 power-rec -> 1024", "3 4 power-rec -> 81", "5 0 power-rec -> 1", "2 1 power-rec -> 2")),
)

# project-euler / codewars extras 124-125
extend(
    (124, "pe-even-fib", "pe-fib-sum", "( limit -- sum )", "even-fibonacci-sum", 4, "project-euler",
     "https://projecteuler.net/problem=2", "scalar-math", "scalar", "PE Even Fibonacci Sum",
     ("Return sum of even Fibonacci terms not exceeding limit.", "Project Euler #2."),
     ("Iterative fib walk.", "limit on stack."),
     ("10 pe-fib-sum -> 10", "34 pe-fib-sum -> 44", "100 pe-fib-sum -> 44")),
    (125, "pe-sum-square", "pe-sum-square", "( n -- diff )", "sum-square-difference", 3, "project-euler",
     "https://projecteuler.net/problem=6", "scalar-math", "scalar", "PE Sum Square Difference",
     ("Return (sum 1..n)^2 - sum of squares 1..n.", "Project Euler #6."),
     ("Closed form or loop.", "n positive."),
     ("10 pe-sum-square -> 2640", "100 pe-sum-square -> 25164150", "1 pe-sum-square -> 0")),
)

# Training-eval optimal extras 126-139 (Forth-heavy blocks: linked, parse, graph, dp, design)
extend(
    (126, "list-partition", "part-list", "( head pivot -- lo-head )", "linked-list-partition", 6, "leetcode",
     "https://leetcode.com/problems/partition-list/", "linked-structure", "linked-cells", "Partition List",
     ("Partition list so values < pivot come before others; return lo-head index.", "Stable relative order within parts."),
     ("In-place index links.", "Uses LINK scaffold."),
     ("1 3 part-list -> 1", "ch-val@ 1 -> 2"),
     LINK + "\n1 1 1 ch-val! 4 ch-next!\n4 3 4 ch-val! 3 ch-next!\n3 2 3 ch-val! 2 ch-next!\n2 5 2 ch-val! 5 ch-next!\n5 0 5 ch-val! 0 ch-next!\n1 constant ch-head"),
    (127, "reorder-list", "reorder-list", "( head -- head' )", "linked-list-reorder", 6, "leetcode",
     "https://leetcode.com/problems/reorder-list/", "linked-structure", "linked-cells", "Reorder List",
     ("Reorder L0..Ln-1 to L0,Ln-1,L1,Ln-2,...", "Return new head index."),
     ("Find middle, reverse second half, merge.",),
     ("1 reorder-list -> 1",),
     LINK + "\n1 2 1 ch-val! 2 ch-next!\n2 3 2 ch-val! 3 ch-next!\n3 4 3 ch-val! 4 ch-next!\n4 5 4 ch-val! 5 ch-next!\n5 0 5 ch-val! 0 ch-next!\n1 constant ch-head"),
    (128, "bf-steps", "bf-steps", "( c-addr u -- steps )", "brainfuck-step-count", 7, "codewars",
     "https://www.codewars.com/kata/526156943dfe7ce06200063e", "parse-interpreter", "string", "Brainfuck Steps",
     ("Run Brainfuck program until halt; return instruction steps executed.", "Tape size 30000; input empty."),
     ("Interpreter loop.", "Use ch-setup for program."),
     ('s" +++" ch-setup bf-steps -> 3', 's" [.-]" ch-setup bf-steps -> 0'),
     's" +." ch-setup bf-steps -> 2'),
    (129, "count-words", "word-count", "( c-addr u -- n )", "token-count-whitespace", 3, "codewars",
     "https://www.codewars.com/kata/515c4fe1ff9373f4b000058a", "parse-interpreter", "string", "Word Count",
     ("Count whitespace-separated tokens in buffer.", "Multiple spaces collapse."),
     ("Single pass.", "Use ch-setup."),
     ('s" one two three" ch-setup word-count -> 3', 's"  a  b " ch-setup word-count -> 2',
      's" " ch-setup word-count -> 0', 's" x" ch-setup word-count -> 1')),
    (130, "union-find", "uf-find", "( i -- root )", "union-find-path-compress", 6, "leetcode",
     "https://leetcode.com/problems/redundant-connection/", "graph", "cell-array", "Union Find Root",
     ("Return root of set containing i using parent[] in ch-data with path compression.", "1-indexed nodes."),
     ("Union in scaffold init.", "uf-find only for tests."),
     ("3 uf-find -> 1", "4 uf-find -> 4", "5 uf-find -> 4"),
     "2 1 ch!  3 1 ch!  4 4 ch!  5 4 ch!\n5 constant ch-n"),
    (131, "topo-len", "topo-len", "( -- n )", "topological-sort-length", 6, "leetcode",
     "https://leetcode.com/problems/course-schedule-ii/", "graph", "cell-array", "Topological Order Length",
     ("Return number of courses in a valid topological order for DAG edges in ch-edges.", "If cycle exists return 0."),
     ("Kahn or DFS topo.", "Preload edges like can-finish."),
     ("topo-len -> 4",),
     "2 1 ch!  3 1 ch!  4 2 ch!  5 3 ch!\n4 constant ch-n-courses"),
    (132, "bt-zigzag", "zigzag-sum", "( root -- sum )", "binary-tree-zigzag-sum", 6, "leetcode",
     "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "trees-bst", "tree-cells",
     "Zigzag Level Sum",
     ("Return sum of values on zigzag level-order traversal.", "Alternating left-right per level."),
     ("BFS with direction flag.", "Uses TREE scaffold."),
     ("1 zigzag-sum -> 45", "2 zigzag-sum -> 27"),
     TREE + "\n3 0 ch-t!  2 1 ch-t!  3 2 ch-t!\n9 3 ch-t!  0 4 ch-t!  0 5 ch-t!\n20 6 ch-t!  4 7 ch-t!  5 8 ch-t!\n15 9 ch-t!  0 10 ch-t!  0 11 ch-t!\n7 12 ch-t!  0 13 ch-t!  0 14 ch-t!\n0 15 ch-t!  0 16 ch-t!  0 17 ch-t!\n1 constant ch-root\n2 constant ch-root-small"),
    (133, "knapsack01", "knapsack01?", "( cap -- flag )", "knapsack-01-exists", 7, "leetcode",
     "https://leetcode.com/problems/subset-sum/", "dynamic-programming", "cell-array",
     "0/1 Knapsack Possible",
     ("Return TRUE if some subset of ch-data sums exactly to cap.", "Each item used at most once."),
     ("Bitset or DP.", "cap on stack."),
     ("5 knapsack01? -> true", "12 knapsack01? -> true", "11 knapsack01? -> true"),
     "1 0 ch!  5 1 ch!  11 2 ch!  5 3 ch!\n4 constant ch-n"),
    (134, "edit-distance", "edit-dist", "( a-addr a-u b-addr b-u -- d )", "levenshtein-distance", 7, "leetcode",
     "https://leetcode.com/problems/edit-distance/", "dynamic-programming", "string", "Edit Distance",
     ("Return minimum edit distance between two strings (insert/delete/replace).", "Use two ch-setup buffers."),
     ("2D DP table.", "Addresses on stack before call."),
     ('s" horse" ed-a-setup s" ros" ed-b-setup edit-dist -> 3',
      's" " ed-a-setup s" a" ed-b-setup edit-dist -> 1',
      's" abc" ed-a-setup s" abc" ed-b-setup edit-dist -> 0'),
     "create ed-a 32 chars allot\n"
     "create ed-b 32 chars allot\n"
     ": ed-a-setup ( c-addr u -- ed-a u )  dup >r ed-a swap move ed-a r> ;\n"
     ": ed-b-setup ( c-addr u -- ed-b u )  dup >r ed-b swap move ed-b r> ;"),
    (135, "lru-get", "lru-get", "( key -- val flag )", "lru-cache-get", 7, "leetcode",
     "https://leetcode.com/problems/lru-cache/", "trie-design", "cell-array", "LRU Get",
     ("Return value and TRUE if key in fixed LRU (capacity 3) after sequence of puts in scaffold.", "Companion words lru-put in scaffold."),
     ("Doubly-linked + hash table.", "Tests call lru-get only."),
     ("2 lru-get -> 2 true", "3 lru-get -> false"),
     ": lru-init ( -- ) ;\n: lru-put ( key val -- ) ;\nlru-init  1 1 lru-put  2 2 lru-put  1 3 lru-put"),
    (136, "run-length-len", "rle-len", "( c-addr u -- out-u )", "run-length-encode-len", 4, "codewars",
     "https://www.codewars.com/kata/23f4a78cfd7d6b08a000056c", "strings", "string", "Run-Length Output Len",
     ("Return byte length of run-length encoding of input (digits + char).", "aaabb -> a3b2 length."),
     ("Single pass.", "Use ch-setup."),
     ('s" aaa" ch-setup rle-len -> 2', 's" aabbb" ch-setup rle-len -> 4', 's" ab" ch-setup rle-len -> 2')),
    (137, "morse-len", "morse-len", "( c-addr u -- n )", "morse-decode-length", 5, "codewars",
     "https://www.codewars.com/kata/5262119038c0985a5b00029", "strings", "string", "Morse Decode Len",
     ("Return length of decoded message from morse string (space-separated codes).", "Invalid -> 0."),
     ("Table lookup.", "Use ch-setup."),
    ('s" .... . -.-- . .-. .." ch-setup morse-len -> 6', 's" -.... . .-.. .-.. --- .--." ch-setup morse-len -> 6')),
    (138, "collatz-steps", "collatz", "( n -- steps )", "collatz-sequence-length", 4, "project-euler",
     "https://projecteuler.net/problem=14", "recursion", "scalar", "Collatz Steps",
     ("Return number of steps to reach 1 in Collatz sequence starting at n.", "n>=1."),
     ("While loop.", "Classic PE pattern."),
     ("1 collatz -> 0", "13 collatz -> 9", "27 collatz -> 111")),
    (139, "sorted-median", "sorted-median", "( -- med )", "median-sorted-array", 7, "leetcode",
     "https://leetcode.com/problems/median-of-two-sorted-arrays/", "binary-search", "cell-array",
     "Median of Sorted Array",
     ("Return median of sorted values in ch-data[0..ch-n).", "Even n: lower-middle element for benchmark."),
     ("Binary search or index math.", "Small n."),
     ("sorted-median -> 3",),
     "1 0 ch!  2 1 ch!  3 2 ch!  4 3 ch!  5 4 ch!  6 5 ch!\n6 constant ch-n"),
)

def write_catalog() -> None:
    import pprint

    challenges = [ch(t) for t in RAW]
    header = '''"""Forth benchmark challenge bank — 139 adapted problems for Gforth."""

from __future__ import annotations

_CHALLENGES: list[dict] = '''
    body = pprint.pformat(challenges, width=100, sort_dicts=False)
    footer = '''


def get_challenges() -> list[dict]:
    """Return challenge specification dicts (currently 139)."""
    return [dict(c) for c in _CHALLENGES]


if __name__ == "__main__":
    cs = get_challenges()
    n = len(cs)
    print(n)
    keys = [c["pattern_key"] for c in cs]
    print("pattern_key unique:", len(keys) == len(set(keys)))
    ids = [c["id"] for c in cs]
    print(f"ids 1..{n}:", ids == list(range(1, n + 1)))
    sources = {}
    for c in cs:
        sources[c["source"]] = sources.get(c["source"], 0) + 1
    print("sources:", sources)
    cogs = [c["cognitive"] for c in cs]
    print("cognitive range:", min(cogs), "-", max(cogs))
'''
    OUT.write_text(header + body + footer, encoding="utf-8")
    print(f"wrote {len(challenges)} challenges -> {OUT}")


if __name__ == "__main__":
    write_catalog()

